name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
          pip install buildozer cython==0.29.33 kivy

      - name: Build APK
        run: |
          # ეს ხაზი გვეტყვის, სად რა ფაილი გვიდევს
          ls -R
          # აქ იწყება აწყობა
          buildozer android debug || echo "Buildozer-მა შეცდომა დაუშვა"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SciencePortal-APK
          path: bin/*.apk
